/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.HashPassWd;
import Models.User;
import Models.Users.Usuario;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Controllers.Controladora;
import Controllers.passwordDifficulty;
import Controllers.passwordGenerator;

/**
 *
 * @author alexandre jastrow da cruz
 */
public class CadastroUsuario extends javax.swing.JFrame {
    
    Controladora contr;
    /**
     * Creates new form CadastroUsuario
     * @param contr
     */
    public CadastroUsuario(Controladora contr) {
        this.contr = contr;
        initComponents();
    }
    
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCadastraUsuario = new javax.swing.JButton();
        jButtonCadastraUsuarioCancel = new javax.swing.JButton();
        jLabelCadastroUsuarioLogin = new javax.swing.JLabel();
        jComboBoxTpUser = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCadastroUsuarioLogin = new javax.swing.JTextField();
        jLabelCadastroUsuarioSenha = new javax.swing.JLabel();
        jPasswordFieldCadastroSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabelCadastroUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButtonCadastraUsuario.setText("Cadastrar");
        jButtonCadastraUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraUsuarioActionPerformed(evt);
            }
        });

        jButtonCadastraUsuarioCancel.setText("Cancela");
        jButtonCadastraUsuarioCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraUsuarioCancelActionPerformed(evt);
            }
        });

        jLabelCadastroUsuarioLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCadastroUsuarioLogin.setText("Login");

        jComboBoxTpUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTpUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Cliente"}));
        jComboBoxTpUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTpUserActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo de Usuario");

        jTextFieldCadastroUsuarioLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelCadastroUsuarioSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCadastroUsuarioSenha.setText("Senha");

        jPasswordFieldCadastroSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordFieldCadastroSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldCadastroSenhaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCadastroUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelCadastroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadastroUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastroUsuario.setText("Cadastro de Usuarios");
        jPanel2.add(jLabelCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 9, 330, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastroUsuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadastraUsuarioCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadastraUsuario)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPasswordFieldCadastroSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCadastroUsuarioLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(jComboBoxTpUser, 0, 166, Short.MAX_VALUE))
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabelCadastroUsuarioLogin)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCadastroUsuarioSenha)
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCadastraUsuario)
                            .addComponent(jButtonCadastraUsuarioCancel))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxTpUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(15, 15, 15)
                    .addComponent(jTextFieldCadastroUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPasswordFieldCadastroSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(128, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(333, 237));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldCadastroSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldCadastroSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldCadastroSenhaActionPerformed

    private void jComboBoxTpUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTpUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTpUserActionPerformed

    private void jButtonCadastraUsuarioCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraUsuarioCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCadastraUsuarioCancelActionPerformed

    private void jButtonCadastraUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraUsuarioActionPerformed

        User n;
        String tpUser = (String) jComboBoxTpUser.getSelectedItem();

        String login = jTextFieldCadastroUsuarioLogin.getText();

        String passw = jPasswordFieldCadastroSenha.getText();

        if(contr.selectUser(login) != null){
            JOptionPane.showMessageDialog(null, "Usuarios Já Cadastrado!!!");
            return;
        }
        if(login.equals("") || passw.equals("")){
            JOptionPane.showMessageDialog(null, "Senha ou login invalido!!!");
            return;
        }

        if(passwordDifficulty.isStrong(passw) == false){
            JOptionPane.showMessageDialog(null, "Senha muito fraca!!!");
            return;
        }
        int tp;

        try {
            String senhaHashada = HashPassWd.gerarHash(passw);

            n = Usuario.newUser(tpUser, login, senhaHashada);

            this.contr.insertUser(n);
            JOptionPane.showMessageDialog(null, "Usuarios "+ login + " Cadastrado com Sucesso!!!");

        } catch (HeadlessException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();

    }//GEN-LAST:event_jButtonCadastraUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroUsuario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastraUsuario;
    private javax.swing.JButton jButtonCadastraUsuarioCancel;
    private javax.swing.JComboBox<String> jComboBoxTpUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCadastroUsuario;
    private javax.swing.JLabel jLabelCadastroUsuarioLogin;
    private javax.swing.JLabel jLabelCadastroUsuarioSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldCadastroSenha;
    private javax.swing.JTextField jTextFieldCadastroUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
