/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Locals.Local;
import javax.swing.JOptionPane;
import Controllers.Controladora;

/**
 *
 * @author alexandre jastrow da cruz
 */
public class CadastroLocal extends javax.swing.JFrame {
    
    Controladora contr;
    /**
     * Creates new form CadastroUsuario
     * @param contr
     */
    public CadastroLocal(Controladora contr) {
        this.contr = contr;
        initComponents();
    }
    
    public CadastroLocal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCadastraUsuario = new javax.swing.JButton();
        jButtonCadastraUsuarioCancel = new javax.swing.JButton();
        jLabelCadastrolocalNumero = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        CadastroLocalCategoria = new javax.swing.JLabel();
        jTextFieldCadastroLocalNumero = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelCadastroUsuario = new javax.swing.JLabel();
        jLabelCadastroLocalNome = new javax.swing.JLabel();
        jTextFieldCadastroLocalNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCadastraUsuario.setText("Cadastrar");
        jButtonCadastraUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastraUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jButtonCadastraUsuarioCancel.setText("Cancela");
        jButtonCadastraUsuarioCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraUsuarioCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastraUsuarioCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabelCadastrolocalNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCadastrolocalNumero.setText("Numero");
        jPanel1.add(jLabelCadastrolocalNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 80, -1));

        jComboBoxCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala", "Quarto", "Cozinha", "Corredor", "Area Externa"}));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 166, -1));

        CadastroLocalCategoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CadastroLocalCategoria.setText("Categoria");
        jPanel1.add(CadastroLocalCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, -1));

        jTextFieldCadastroLocalNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldCadastroLocalNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 166, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCadastroUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelCadastroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadastroUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastroUsuario.setText("Cadastro de Locais");
        jPanel2.add(jLabelCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 9, 330, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 333, 58));

        jLabelCadastroLocalNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCadastroLocalNome.setText("Nome");
        jPanel1.add(jLabelCadastroLocalNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 52, -1));

        jTextFieldCadastroLocalNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldCadastroLocalNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 166, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(333, 253));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastraUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraUsuarioActionPerformed
        
        Local l;
        
        String categoria = (String) jComboBoxCategoria.getSelectedItem();
        
        String nome = jTextFieldCadastroLocalNome.getText();
        
        int numero = Integer.parseInt(jTextFieldCadastroLocalNumero.getText());
        
        l = new Local(categoria, nome, numero);
        
        
        this.contr.insertLocal(l);
        JOptionPane.showMessageDialog(null, "Local " + nome + " Cadastrado com Sucesso!!!");
        dispose();

    }//GEN-LAST:event_jButtonCadastraUsuarioActionPerformed

    private void jButtonCadastraUsuarioCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraUsuarioCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCadastraUsuarioCancelActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroLocal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastroLocalCategoria;
    private javax.swing.JButton jButtonCadastraUsuario;
    private javax.swing.JButton jButtonCadastraUsuarioCancel;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabelCadastroLocalNome;
    private javax.swing.JLabel jLabelCadastroUsuario;
    private javax.swing.JLabel jLabelCadastrolocalNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCadastroLocalNome;
    private javax.swing.JTextField jTextFieldCadastroLocalNumero;
    // End of variables declaration//GEN-END:variables
}
